### ISSUE TITLE
demo啥时候有呢

### ISSUE THREAD

**Issue by excxapp** [smilecc/think-graphql#1]
如题
thinkphp 中如何使用

**Comment by smilecc** [comment]
会尽快更新的

**Comment by excxapp** [comment]
可以给一个简单的demo吗，不用复杂，主要是现在不会用，给一个model/controller绑定的即可

**Comment by smilecc** [comment]
@cmideal 好的，最快今晚出

**Comment by smilecc** [comment]
@cmideal 已经更新demo，https://github.com/smilecc/think-graphql-demo

**Comment by excxapp** [comment]
好的，大神辛苦了，我先看一下哈，不懂的再咨询您
