### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by excxapp** [smilecc/think-graphql#2]
The requested package smilecc/think-graphql could not be found in any version, there may be a typo in the package name.

**Comment by smilecc** [comment]
请使用 `composer require smilecc/think-graphql:dev-master` 来安装，如果你用了 https://www.phpcomposer.com/ 的镜像，那么他们的镜像有点问题。请使用原本的镜像或者使用Laravel China提供的镜像， https://laravel-china.org/composer
