### ISSUE TITLE
请求接口出现 "error": "query is empty!"

### ISSUE THREAD

**Issue by dafa168** [smilecc/think-graphql#4]
1、composer 安装后 并设置command 并 init 。
2、访问 http://localhost/api/graph ，结果显示：
{
  "error": "query is empty!"
}
 
麻烦看看哈。

**Comment by smilecc** [comment]
请使用 https://chrome.google.com/webstore/detail/chromeiql/fkkiamalmpiidkljmicmjfbieiclmeij 工具来访问，在使用 think-graphql 之前，请了解 GraphQL
